### ISSUE TITLE
Improper redirect after completing Affirm loan authorization

### ISSUE THREAD

**Issue by modded-nate** [solidusio/solidus_affirm#67]
We've had a number of incomplete orders with completed Affirm loan authorizations. In many instances, our customers are stating that they were not redirected back to the site correctly (we've had some complaints that they were redirected to the homepage, others saying that they were directed to an account sign up page). Because the Affirm portion takes you offsite, I'm unable to capture the behavior. I'm curious if anyone else has had this issue come up and if so, do you have any insight?

**Comment by jarednorman** [comment]
I don't think I've seen this. @AlistairNorman You seen anything like this?

**Comment by AlistairNorman** [comment]
I haven't encountered any issues like this. My only suggestion would be to try to reproduce it using a test account. Affirm offers test api keys and a sandbox environment that could be helpful. 

That being said, the changes I made to the gem should make it impossible (unless you've set up your checkout differently) to have Affirm authorizations on uncompleted orders. @modded-nate is your gem up to date? The authorization and capture should now both happen when the order is completed instead of the authorization happening before the order is completed.

**Comment by AlistairNorman** [comment]
@modded-nate I've run into a similar issue because if the customer is not signed in then Solidus relies on a guest token to track the order that should be loaded when the user is redirected back after the going to Affirm. This is stored as a cookie so if they have cookies disabled then it likely can't find the guest token. There is a fallback that just goes to the user's last incomplete order but if it's a guest checkout then that can't be used either.

I'm told that there was a recent update to some of Chrome's cookie policy that could be affecting this. I'm not sure of the best solution, it's not a problem with this gem in particular so much as a problem generally with tracking users as they go off site. I would be open to any solutions we could look at here, I'm not sure of how we would go about addressing this.

**Comment by modded-nate** [comment]
@AlistairNorman Sorry I didn't respond on this earlier. We have not upgraded to the most recent gem that completes the authorization and order at the same time. My concern with that flow (without knowing if it's actually founded in anything) is that if we are experiencing inconsistent redirects then we might be preventing orders from being completed if the user is unsure what happened or how they were directed to a different part of the site. At present, we can at least see complete Affirm authorizations and compare those to completed orders and try an abandoned cart lie tactic to try and confirm the order, whereas with the updated gem we would not have those Affirm authorizations to look into further.

Your most recent comment makes sense. I'm not sure how to go about addressing the issue of checkout flows that go off site, but more wanted to make sure I wasn't on a wild goose chase. We've also had somewhat related issues with regards to analytics programs losing attribution when using payment methods like Affirm or PayPal that leave the site before returning back to the checkout flow. My first thought (without having a ton of technical knowledge) would be to see if there was a way to embed the redirect to the third party payment method in something like an iframe or modal, but I don't know how feasible this is with the given code.

Since this seems to be more of an issue of leaving the site rather than the Affirm gem specifically, we can probably close this issue as it probably belongs somewhere else more related to the problem.

**Comment by AlistairNorman** [comment]
@modded-nate If people are being redirected to the wrong place after authorization then their orders shouldn't be completed yet right? Without seeing your checkout flow, what I would expect to happen when you're using the old version of the gem is that you would end up with authorizations that are never captured unless you are completing orders before payment?

Yeah I think we can probably close the issue. Are you in the Solidus Slack? If you want to keep talking about solutions we could move there and open it up to anyone else who might have ideas.

**Comment by modded-nate** [comment]
@AlistairNorman that's correct. We're contacting customers that have completed authorizations but have not completed the order to verify that they would like to complete the order. If they respond and od want to complete the order, we are confirming in our backend to complete the order. It's a manual process but we have been able to save a decent number of orders.

I will close this now and bring it up in the Solidus slack channel at some point in the near future. Thanks for looking into it!
